FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# serviceagenda

Service Agenda is a simple API allowing users to magage their agendas.


# Group User

Resource operations related to a user in the API.

## User-Key [/v1/user/getkey{?username,password}]

+ Parameters

    - username : `root` (string, required) - User Name
    - password : `pass` (required)

### Get User Key [GET]

get a security key for operations later

+ Response 200 (application/json)

        {
            "key":"1e3576bt",
            "status": true,
            "message": "get key successfully"
        }

# Group Users

Resources related to users in the API.

## Users Collection [/v1/users{?key,limit}]

+ Parameters
    - key : `1e3576bt` (string, required)
    - limit : 2 (int, required)

### List all Users [GET]

+ Response 200 (application/json)

        [
            {
                "id":1，
                "username":"zhang3"，
                "password":"zhang"，
                "phone":"12345678902"，
                "email":"zhang3@mail2.sysu.edu.cn"，
            },{
                "id":2，
                "username":"li4"，
                "password":"li"，
                "phone":"12345678901"，
                "email":"li4@mail2.sysu.edu.cn"，
            }
        ]

### Create a New User [POST]

+ Request (application/json)

        {
            "username":"zhang3",
            "password":"zhang",
            "phone":"12345678901",
            "email":"zhang3@mail2.sysu.edu.cn",
        }

+ Response 201 (application/json)

    - Headers

            Location: /users/1

    - Body

            {
                "status": true,
                "message": "create user successfully"
            }

### Get User by ID [GET /v1/users/{?id,key}]

+ Parameters
    - key : `1e3576bt` (string, required)
    - id : `1` (int, required) - User Name

+ Response 200 (application/json)

        {
            "id" : 1,
            "username":"zhang3",
            "password":"zhang",
            "phone":"12345678901",
            "email":"zhang3@mail2.sysu.edu.cn",
        }
### Delete a User [DELETE /v1/users/{?key}]

+ Parameters
    - key : `1e3576bt` (string, required)

+ Response 200 (application/json)

        {
            "status": true,
            "message": "get key successfully"
        }


# Group Meetings

Resources related to meetings in the API.

## Meetings Collection [/v1/meetings/create/{?key}]

+ Parameters

    - key : `1e3576bt` (string, required)

### Create a new meeting [POST]

+ Request (application/json)

        {
            "title":"emmmmmm",
            "sponsor":"zhang3",
            "participators":"user1 user2 user3",
            "starttime":"YYYY-MM-DD HH:MM:SS",
            "endtime":"YYYY-MM-DD HH:MM:SS"
        }

+ Response 201 (application/json)

    - Headers

            Location: /meetings/emmmmmm

    - Body

            {
                "status": true,
                "message": "create meeting successfully"
            }