FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# serviceagenda

Service Agenda is a simple API allowing users to magage their agendas.


# Group User

Resources related to a user in the API.

## User-Key [/v1/user/getkey{?username,password}]


+ Parameters
    - username : `root` (string, required) - User Name
    - password : `pass` (required)

### Get User Key [GET]

get a security key for operations later

+ Response 200 (application/json) 

    
        {
            "key":"h12bhj53"
            "permissions":["user","admin"]
        }


# Group Users

Resources related to users in the API.

### List all Users [GET]

+ Response 200 (application/json)

        [
            {
                "id":1
                "username":"freakkid"
                "password":"kidissad"
                "email":"freakkid@mail.sysu.edu.cn"
            },{
                "id":2
                "username":"freakkid1"
                "password":"kidissad1"
                "email":"freakkid1@mail.sysu.edu.cn"
            }
        ]

### Create a New User [POST]

+ Response 201 (application/json)
    
    + Headers
    
            Locations: /users/1
        
    + Body
    
            {
                "id":1
                "username":"freakkid"
                "password":"kidissad"
                "email":"freakkid@mail.sysu.edu.cn"
            }

### Get User by ID [GET /v1/users/{id}]

+ Parameters
    - id : `1` (int, required) - User Name
    
+ Response 200 (application/json)

        {
            "id":1
            "username":"freakkid"
            "password":"kidissad"
            "email":"freakkid@mail.sysu.edu.cn"
        }